class com.stripe.android.compat.AsyncTask$3 extends java.util.concurrent.FutureTask
{
    final com.stripe.android.compat.AsyncTask this$0;

    void <init>(com.stripe.android.compat.AsyncTask, java.util.concurrent.Callable)
    {
        com.stripe.android.compat.AsyncTask$3 $r0;
        com.stripe.android.compat.AsyncTask $r1;
        java.util.concurrent.Callable $r2;

        $r0 := @this: com.stripe.android.compat.AsyncTask$3;

        $r1 := @parameter0: com.stripe.android.compat.AsyncTask;

        $r2 := @parameter1: java.util.concurrent.Callable;

        $r0.<com.stripe.android.compat.AsyncTask$3: com.stripe.android.compat.AsyncTask this$0> = $r1;

        specialinvoke $r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }

    protected void done()
    {
        com.stripe.android.compat.AsyncTask$3 $r0;
        java.lang.InterruptedException $r1;
        java.util.concurrent.ExecutionException $r2;
        java.util.concurrent.CancellationException $r3;
        java.lang.Object $r4;
        com.stripe.android.compat.AsyncTask $r5, $r5_1, $r5_2, $r5_3, $r5_4, $r5_5;
        java.lang.RuntimeException $r6, $r6_1;
        java.lang.Throwable $r7, $r7_1;

(0)     $r0 := @this: com.stripe.android.compat.AsyncTask$3;

     label1:
        $r4 = virtualinvoke $r0.<com.stripe.android.compat.AsyncTask$3: java.lang.Object get()>();

     label2:
        $r5 = $r0.<com.stripe.android.compat.AsyncTask$3: com.stripe.android.compat.AsyncTask this$0>;

     label3:
        staticinvoke <com.stripe.android.compat.AsyncTask: void access$400(com.stripe.android.compat.AsyncTask,java.lang.Object)>($r5, $r4);

     label4:
        return;

     label5:
        $r1 := @caughtexception;

        $r5_1 = Phi($r5 #0);

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r1);

        return;

     label6:
        $r2 := @caughtexception;

        $r5_2 = Phi($r5 #0);

        $r6 = new java.lang.RuntimeException;

        $r7 = virtualinvoke $r2.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r7);

        throw $r6;

     label7:
        $r3 := @caughtexception;

        $r5_3 = Phi($r5 #0);

        $r5_4 = $r0.<com.stripe.android.compat.AsyncTask$3: com.stripe.android.compat.AsyncTask this$0>;

        staticinvoke <com.stripe.android.compat.AsyncTask: void access$400(com.stripe.android.compat.AsyncTask,java.lang.Object)>($r5_4, null);

        return;

     label8:
        $r7_1 := @caughtexception;

        $r5_5 = Phi($r5 #0);

        $r6_1 = new java.lang.RuntimeException;

        specialinvoke $r6_1.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r7_1);

        throw $r6_1;

        catch java.lang.InterruptedException from label1 to label2 with label5;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label6;
        catch java.util.concurrent.CancellationException from label1 to label2 with label7;
        catch java.lang.Throwable from label1 to label2 with label8;
        catch java.lang.InterruptedException from label3 to label4 with label5;
        catch java.util.concurrent.ExecutionException from label3 to label4 with label6;
        catch java.util.concurrent.CancellationException from label3 to label4 with label7;
        catch java.lang.Throwable from label3 to label4 with label8;
    }
}
