public class org.apache.http.auth.MalformedChallengeException extends org.apache.http.ProtocolException
{

    public void <init>()
    {
        org.apache.http.auth.MalformedChallengeException r0;
        java.lang.RuntimeException $r1;

        r0 := @this: org.apache.http.auth.MalformedChallengeException;

        specialinvoke r0.<org.apache.http.ProtocolException: void <init>()>();

        $r1 = new java.lang.RuntimeException;

        specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.String)>("Stub!");

        throw $r1;
    }

    public void <init>(java.lang.String)
    {
        org.apache.http.auth.MalformedChallengeException r0;
        java.lang.String r1;
        java.lang.RuntimeException $r2;

        r0 := @this: org.apache.http.auth.MalformedChallengeException;

        r1 := @parameter0: java.lang.String;

        specialinvoke r0.<org.apache.http.ProtocolException: void <init>()>();

        $r2 = new java.lang.RuntimeException;

        specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>("Stub!");

        throw $r2;
    }

    public void <init>(java.lang.String, java.lang.Throwable)
    {
        org.apache.http.auth.MalformedChallengeException r0;
        java.lang.String r1;
        java.lang.Throwable r2;
        java.lang.RuntimeException $r3;

        r0 := @this: org.apache.http.auth.MalformedChallengeException;

        r1 := @parameter0: java.lang.String;

        r2 := @parameter1: java.lang.Throwable;

        specialinvoke r0.<org.apache.http.ProtocolException: void <init>()>();

        $r3 = new java.lang.RuntimeException;

        specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>("Stub!");

        throw $r3;
    }
}
